use web_time::Instant;

use crate::core::{Cell, GameMode};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppAction {
    TogglePause,
    Reset(GameMode),
    ResetCurrent,
    CycleMode,
    CopyState,
    PasteState,
    RequestScreenshot,
    ToggleGhost(bool),
    ToggleAutoColor(bool),
    ToggleAutoLockOnGround(bool),
    SetVolume(u8),
    SelectSkin(String),
    SelectTexture(String),
    ApplySettings,
    ConfirmSettings,
    CancelSettings,
    MoveLeftPress(Instant),
    MoveLeftRelease,
    MoveRightPress(Instant),
    MoveRightRelease,
    SoftDropPress(Instant),
    SoftDropRelease,
    HardDrop,
    RotateCcw,
    RotateCw,
    Rotate180,
    Hold,
    Undo,
    Redo,
    SetEditColor(Cell),
    ClearBoard,
    ToggleHighlightMode,
    ClearHighlight,
    EditCell(i32, i32, Cell),
    EditHighlightCell(i32, i32, u8),
    StartBagEdit,
    ApplyBagEdit(String),
    CancelBagEdit,
    StartHoldEdit(String),
    ApplyHoldEdit(String),
    CancelHoldEdit,
}
